version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./etc/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - edgekv-data:/data
volumes:
  edgekv-data:
